# Generated by Django 5.2 on 2025-04-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_territories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='territory',
            field=models.ForeignKey(blank=True, help_text='Sales territory this user belongs to, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='sales_territories.territory'),
        ),
    ]
