# Generated by Django 5.2 on 2025-04-12 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('crm_entities', '0004_alter_contact_email_alter_contact_first_name_and_more'),
        ('sales_pipeline', '0003_alter_quote_options_quote_account_quote_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User who made or is primarily associated with the call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='call',
            name='related_to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm_entities.account', verbose_name='Related Account'),
        ),
        migrations.AlterField(
            model_name='call',
            name='related_to_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm_entities.contact', verbose_name='Related Contact'),
        ),
        migrations.AlterField(
            model_name='call',
            name='related_to_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='sales_pipeline.deal', verbose_name='Related Deal'),
        ),
        migrations.AlterField(
            model_name='call',
            name='related_to_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm_entities.lead', verbose_name='Related Lead'),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('HELD', 'Held'), ('NOT_HELD', 'Not Held / Cancelled')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User primarily responsible for this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='End time is optional', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='related_to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='crm_entities.account', verbose_name='Related Account'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='related_to_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='crm_entities.contact', verbose_name='Related Contact'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='related_to_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='sales_pipeline.deal', verbose_name='Related Deal'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='related_to_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='crm_entities.lead', verbose_name='Related Lead'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('HELD', 'Held'), ('NOT_HELD', 'Not Held / Cancelled')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User responsible for completing the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date the task is expected to be completed', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm_entities.account', verbose_name='Related Account'),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_to_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm_entities.contact', verbose_name='Related Contact'),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_to_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sales_pipeline.deal', verbose_name='Related Deal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_to_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm_entities.lead', verbose_name='Related Lead'),
        ),
    ]
