# Generated by Django 5.2 on 2025-04-14 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='The target sales amount (e.g., in PHP) for the period', max_digits=14)),
                ('start_date', models.DateField(help_text='The first day of the target period')),
                ('end_date', models.DateField(help_text='The last day of the target period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The sales user this target applies to', on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Target',
                'verbose_name_plural': 'Sales Targets',
                'ordering': ['user', '-start_date'],
            },
        ),
    ]
