# Generated by Django 5.2 on 2025-04-11 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sales territory', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the territory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Manager responsible for this territory (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_territories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Territory',
                'verbose_name_plural': 'Territories',
                'ordering': ['name'],
            },
        ),
    ]
