# Generated by Django 5.2 on 2025-04-11 09:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_entities', '0002_account_territory_lead_territory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or title of the deal', max_length=255)),
                ('stage', models.CharField(choices=[('PROSPECTING', 'Prospecting'), ('QUALIFICATION', 'Qualification'), ('PROPOSAL', 'Proposal/Quote Sent'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='PROSPECTING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Estimated or actual value of the deal', max_digits=12)),
                ('currency', models.CharField(default='PHP', help_text='Currency code (e.g., PHP, USD)', max_length=3)),
                ('close_date', models.DateField(help_text='Expected or actual closing date')),
                ('probability', models.IntegerField(default=10, help_text='Probability of closing the deal (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='The account this deal is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm_entities.account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('primary_contact', models.ForeignKey(blank=True, help_text='Primary contact person for this deal (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm_entities.contact')),
            ],
            options={
                'verbose_name': 'Deal / Opportunity',
                'verbose_name_plural': 'Deals / Opportunities',
                'ordering': ['-close_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(help_text='Unique identifier for the quote', max_length=50, unique=True)),
                ('valid_until', models.DateField(help_text='Date the quote expires')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PRESENTED', 'Presented'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount of the quote', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Account the quote is for', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm_entities.account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, help_text='Contact person the quote is addressed to (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='crm_entities.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, help_text='Deal this quote is associated with (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='sales_pipeline.deal')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
