# Generated by Django 5.2 on 2025-04-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={},
        ),
        migrations.RemoveField(
            model_name='quote',
            name='account',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_id',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier for the deal (e.g., DEAL-0001)', max_length=20, null=True, unique=True, verbose_name='Deal ID'),
        ),
    ]
