# Generated by Django 5.2 on 2025-04-11 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_entities', '0004_alter_contact_email_alter_contact_first_name_and_more'),
        ('sales_pipeline', '0002_alter_quote_options_remove_quote_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AddField(
            model_name='quote',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account the quote is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm_entities.account'),
        ),
        migrations.AddField(
            model_name='quote',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact person the quote is addressed to (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='crm_entities.contact'),
        ),
        migrations.AddField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='Deal this quote is associated with (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='sales_pipeline.deal'),
        ),
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the quote', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PRESENTED', 'Presented'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount of the quote', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Date the quote expires', null=True),
        ),
    ]
