# Generated by Django 5.2 on 2025-04-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0003_alter_quote_options_quote_account_quote_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='quote',
            name='presented_date',
            field=models.DateField(blank=True, help_text='Date the quote was presented to the client', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='validity_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days the quote is valid after presentation date'),
        ),
    ]
