# Generated by Django 5.2 on 2025-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0004_remove_quote_valid_until_quote_presented_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier for the deal', max_length=20, null=True, unique=True, verbose_name='Deal ID'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='probability',
            field=models.IntegerField(default=10, editable=False, help_text='Probability of closing (determined by Stage)'),
        ),
    ]
