# Generated by Django 5.2 on 2025-04-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_entities', '0004_alter_contact_email_alter_contact_first_name_and_more'),
        ('sales_pipeline', '0005_alter_deal_deal_id_alter_deal_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='account',
            field=models.ForeignKey(blank=True, editable=False, help_text='Account the quote is for (derived from Deal)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm_entities.account'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='deal',
            field=models.ForeignKey(help_text='Deal this quote is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='sales_pipeline.deal'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier (e.g., Q-25-0001)', max_length=20, null=True, unique=True, verbose_name='Quote ID'),
        ),
    ]
