# Generated by Django 5.2 on 2025-04-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_pipeline', '0006_alter_quote_account_alter_quote_deal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier (e.g., D25-00001)', max_length=20, null=True, unique=True, verbose_name='Deal ID'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique identifier (e.g., Q-25-00001)', max_length=20, null=True, unique=True, verbose_name='Quote ID'),
        ),
    ]
