# Generated by Django 5.2 on 2025-04-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_entities', '0001_initial'),
        ('sales_territories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='territory',
            field=models.ForeignKey(blank=True, help_text='Territory this account belongs to (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_in_territory', to='sales_territories.territory'),
        ),
        migrations.AddField(
            model_name='lead',
            name='territory',
            field=models.ForeignKey(blank=True, help_text='Territory this lead belongs to (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_in_territory', to='sales_territories.territory'),
        ),
    ]
