# Generated by Django 5.2 on 2025-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_entities', '0002_account_territory_lead_territory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_phone_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile Phone 1'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile Phone 2'),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Work Phone'),
        ),
        migrations.AddField(
            model_name='lead',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile_phone_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile Phone 1'),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile_phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile Phone 2'),
        ),
        migrations.AddField(
            model_name='lead',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Work Phone'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary company phone number', max_length=20),
        ),
    ]
