# Generated by Django 5.2 on 2025-04-18 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_entities', '0005_alter_contact_work_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +6388019525).', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address (e.g., user@example.com).', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone_1',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +639088835511).', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone_2',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +639088835511).', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address (e.g., user@example.com).', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile_phone_1',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +6388019525).', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile_phone_2',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +6388019525).', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., +6388019525).', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
