# Generated by Django 5.2 on 2025-05-04 12:52

from django.db import migrations, models

def migrate_status_values(apps, schema_editor):
    Account = apps.get_model('crm_entities', 'Account')
    status_map = {
        'Prospect': 'PROSPECT',
        'Active': 'ACTIVE',
        'Inactive': 'INACTIVE',
        'Customer': 'CUSTOMER',
        'Partner': 'PARTNER',
        'Former': 'FORMER',
    }
    for account in Account.objects.all():
        if account.status in status_map:
            account.status = status_map[account.status]
            account.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crm_entities', '0006_alter_account_phone_number_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[
                ('ACTIVE', 'Active'),
                ('INACTIVE', 'Inactive'),
                ('PROSPECT', 'Prospect'),
                ('CUSTOMER', 'Customer'),
                ('PARTNER', 'Partner'),
                ('FORMER', 'Former Customer')
                ],
                default='PROSPECT',
                max_length=50
            ),
        ),
    ]
